site_name: Seagull Docs

site_url: /

dev_addr: '0.0.0.0:8000'

site_description: Documentation for fast and lightweight Docker container based virtualization framework.

repo_url: https://github.com/tobegit3hub/seagull

docs_dir: zh #en

#include_search: true

use_absolute_urls: true

#theme: readthedocs

#copyright: Copyright &copy; 2014, <a href="https://twitter.com/_tomchristie">Tom Christie</a>.
#google_analytics: ['UA-27795084-5', 'mkdocs.org']

pages:

# Home
- ['index.md', 'Home']

# User Guide

- ['user_guide/2014-10-13-similar-docker-projects.md', 'User Guide', 'Similar Docker Projects']
- ['user_guide/2014-10-15-seagull-containers-page.md', 'User Guide', 'Seagull Container Page']
- ['user_guide/2014-10-16-seagull-images-page.md', 'User Guide', 'Seagull Images Page']
- ['user_guide/2014-10-17-seagull-configuration-page.md', 'User Guide', 'Seagull Configuration Page']
- ['user_guide/2014-10-19-seagull-dockerhub-page.md', 'User Guide', 'Seagull DockerHub Page']

# Development
- ['development/2014-10-12-access-docker-remote-api.md', 'Development', 'Access Docker Remote API']
- ['development/2014-10-14-seagull-design-and-implement.md', 'Development', 'Seagull Design And Implement']
- ['development/2014-10-18-implement-i18n-with-angular-translate.md', 'Development', 'Implement I18n With Angular Translate']
- ['development/2014-10-20-write-seagull-dockerfile.md', 'Development', 'Write Seagull Dockerfile']
- ['development/2014-10-21-use-godep-to-manage-dependency.md', 'Development', 'Use Godep To Manage Dependency']
- ['development/2014-10-22-implement-search-with-angular.md', 'Development', 'Implement Search With Angular']
- ['development/2014-10-23-use-beego-as-web-server.md', 'Development', 'Use Beego As Web Server']
- ['development/2014-10-24-use-beego-as-api-server.md', 'Development', 'Use Beego As API Server']
- ['development/2014-10-25-use-angularjs.md', 'Development', 'Use AngularJS']
- ['development/2014-10-26-use-bower-to-manage-dependency.md', 'Development', 'Use Bower To Manage Dependency']
- ['development/2014-10-27-how-seagull-use-bootstrap.md', 'Development', 'How Seagull Use Bootstrap']
- ['development/2014-10-28-use-jquerygritter-for-notification.md', 'Development', 'Use JQuery.Gritter For Notification']
- ['development/2014-10-29-implement-angular-filter.md', 'Development', 'Implement Angular Filter']
- ['development/2014-10-30-use-animate-css.md', 'Development', 'Use Animate.css']
- ['development/2014-11-02-use-drone-for-ci.md', 'Development', 'Use Drone For CI']

